export const BUY_BOOK="BUY_BOOK"
export const SELL_BOOK="SELL_BOOK"
export const BUY_BOOK_SUCCESS="BUY_BOOK_SUCCESS"
export const SELL_BOOK_SUCCESS="SELL_BOOK_SUCCESS"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";